export const ERROR_CODES = {
  // 7.1 인증 에러
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_INSUFFICIENT_PERMISSION: "AUTH_INSUFFICIENT_PERMISSION",

  // 7.2 데이터 에러
  DATA_FAMILY_NOT_FOUND: "DATA_FAMILY_NOT_FOUND",
  DATA_USER_NOT_FOUND: "DATA_USER_NOT_FOUND",
  DATA_MEMBER_LIMIT_EXCEEDED: "DATA_MEMBER_LIMIT_EXCEEDED",

  // 7.3 정책 에러
  POLICY_USER_BLOCKED: "POLICY_USER_BLOCKED",
  POLICY_QUOTA_EXCEEDED: "POLICY_QUOTA_EXCEEDED",
  POLICY_TIME_BLOCKED: "POLICY_TIME_BLOCKED",
  POLICY_ALREADY_BLOCKED: "POLICY_ALREADY_BLOCKED",

  // 7.4 시스템 에러
  SYS_INTERNAL_ERROR: "SYS_INTERNAL_ERROR",
  SYS_REDIS_UNAVAILABLE: "SYS_REDIS_UNAVAILABLE",
  SYS_RATE_LIMIT_EXCEEDED: "SYS_RATE_LIMIT_EXCEEDED",
  SYS_SERVICE_UNAVAILABLE: "SYS_SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorResponse {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
  errorMessage: string;
}
